### ISSUE TITLE
Error: The style-loader cannot be used in a non-browser environment

### ISSUE THREAD

**Issue by amiral84** [andyyou/react-coverflow#10]
I have installed coverflow and I have MERN stack in use. I get following error whenever I want to start my project by using `npm start`:

`Error: The style-loader cannot be used in a non-browser environment`

What's the reason for that issue and how I can solve it? I have been searching on internet but still didn't found any working solution. #

**Comment by battuashwik** [comment]
Any update on this. Having the same issue.

**Comment by andyyou** [comment]
Sorry for that I focus on working and change to vue.js currently so have no time to update.
But I will attempt to fix problem

**Comment by Asalem1** [comment]
@amilajack & @battuashwik - try pulling the newest branch and LMK if it works. I've just updated the packages and removed some of the deprecated packages.
