### ISSUE TITLE
Changing active prop doesn't reflect in the UI 

### ISSUE THREAD

**Issue by ahmedlhanafy** [andyyou/react-coverflow#11]
So my scenario is I set active prop to some state and changing this state variable doesn't reflect in the UI

**Comment by andyyou** [comment]
I forgot to handle `componentWillReceiveProps` so that I fixed this issue

**Comment by ahmedlhanafy** [comment]
@andyyou Is it fixed in NPM now?

**Comment by andyyou** [comment]
Yap you can see new example page at the bottom and the version is 0.2.2
