### ISSUE TITLE
Disabled prop

### ISSUE THREAD

**Issue by ahmedlhanafy** [andyyou/react-coverflow#13]
I think one important prop that is missing is disabled and it can be done easily by changing only the pointer-events to none when this prop is true

**Comment by andyyou** [comment]
@ahmedlhanafy You mean disable click ability of image?

**Comment by ahmedlhanafy** [comment]
Yes i may want to disable user from changing the covers @andyyou

**Comment by andyyou** [comment]
@ahmedlhanafy  Do you need disable for each image or just turn off all click feature of image.
BTW Thanks ur pr I merged.

**Comment by ahmedlhanafy** [comment]
No I want to disable clicking the whole thing @andyyou

**Comment by andyyou** [comment]
OK I got it

**Comment by andyyou** [comment]
@ahmedlhanafy You can use `clickable` props now on v0.2.3

**Comment by ahmedlhanafy** [comment]
@andyyou Thanks man

**Comment by ahmedlhanafy** [comment]
@andyyou This doesn't work man, have you tested it?
