### ISSUE TITLE
install react problem

### ISSUE THREAD

**Issue by roth1002** [andyyou/react-coverflow#14]
when I run below

```
npm i 
```

I always got 

```
├── UNMET PEER DEPENDENCY react@15.3.2 extraneous
└── UNMET PEER DEPENDENCY react-dom@^15.3.1
```

and

```
npm WARN react-coverflow@0.2.3 requires a peer of react-dom@^15.3.1 but none was installed.
npm WARN react-tap-event-plugin@0.2.2 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-coverflow@0.2.3 No repository field.
npm ERR! code 1
```

Seems like reactjs version conflict between react-tap-event-plugin@0.2.2 and this project

**Comment by andyyou** [comment]
@roth1002 you mean you clone this project and excute `npm i`?

**Comment by Asalem1** [comment]
@roth1002 I'm currently working on updating the dependencies, I'll let you know when it's up and running

**Comment by Asalem1** [comment]
@roth1002  v0.2.5 should resolve the issues. LMK if you encounter any problems
