### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by devinholloway** [andyyou/react-coverflow#16]
Decided to give the new version a try. Using the same github code example, when I run the example I get:

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by devinholloway** [comment]
Nevermind. It was my problem. You can close this. Thanks!

**Comment by Natasha08** [comment]
@devinholloway, can you share how you fixed your issue, because I am getting the same error message.

**Comment by devinholloway** [comment]
Sure. In my case, it was a lack of React knowledge. I was trying to pass <img> elements in string form (surrounded by quotes), rather than the actual <img> objects themselves. For example:

var photos = gallery.map(function(photo {
   return '<img src="' + photo.url + '"/>';
}));
<Coverflow ...>
  {photos}
</Coverflow/>

I had to get rid of those single quotes around the <img> elements.
