### ISSUE TITLE
Using different sized images?

### ISSUE THREAD

**Issue by devinholloway** [andyyou/react-coverflow#17]
Is there any easy way load images of a different size? I've noticed that if I specify a 'height' on the HTML img elements, it does increase the height. However, specifying 'width' on the images has no affect. It appears that in order to make the images wider, you have to make the coverflow component wider

**Comment by Asalem1** [comment]
@devinholloway I'll take a look at this

**Comment by Asalem1** [comment]
Fixed with most recent push https://github.com/andyyou/react-coverflow/commit/81626974e293712cf6eed429ad1e7be5189dacf2
