### ISSUE TITLE
issue of center active image in container. 

### ISSUE THREAD

**Issue by martingg88** [andyyou/react-coverflow#2]
it doesn't center active image if you have more than 28 images in container. any idea how to solve this?

**Comment by andyyou** [comment]
@martingg88  Thanks for provide issues and sorry for reply late. I will figure out other way to deal this problem.

**Comment by andyyou** [comment]
When I develop this component I only think keep things simple so your images need to be odd number for now

**Comment by andyyou** [comment]
@martingg88 please try v0.1.3

**Comment by martingg88** [comment]
i try to add fake dom to make even stay in odd number.

**Comment by andyyou** [comment]
@martingg88 It's no longer need to do that, I add offset variable to deal with that even or odd number

**Comment by martingg88** [comment]
ok. thanks for your effort.

**Comment by martingg88** [comment]
i don't the offset will work in smaller screen like 320 and 480 width.

**Comment by andyyou** [comment]
ok I will figure out the problem

**Comment by andyyou** [comment]
@martingg88  ![](http://i.imgur.com/z5yAalQ.png) I am test your problem is not problem could your provide demo example

**Comment by andyyou** [comment]
@martingg88 I already add responsive example and items of even number. You can see [demo](http://andyyou.github.io/react-coverflow/)

**Comment by martingg88** [comment]
thanks. will try it again.
