### ISSUE TITLE
Some error about updateDimensions function

### ISSUE THREAD

**Issue by hkchiang** [andyyou/react-coverflow#21]
When using the  coverflow component as content in the panel component, and resize my Chrome Browser , it will show error as follows

Uncaught Error: findDOMNode was called on an unmounted component.
    at invariant (react-with-addons.js:20277)
    at Object.findDOMNode (react-with-addons.js:17766)
    at Coverflow.updateDimensions (Coverflow.js:120)
    at Coverflow.eval (makeAssimilatePrototype.js:15)

It looks like there's some things wrong with resize action, but in fact view and function work as well
need some suggestion..
 
Thanks for your help.

**Comment by Asalem1** [comment]
Hi @hkchiang, could you please pull the most recent branch and let me know if the error persists. I can't seem to recreate it on my end
