### ISSUE TITLE
ES6 Updates?

### ISSUE THREAD

**Issue by cooganb** [andyyou/react-coverflow#30]
Hi team! First, thanks so much for this product. I'm working with it now and it's making my react super UI pretty.

I installed version 0.2.3 from npm and I'm getting deprecation warnings in my browser concerning the use of React.createclass. The more recent use cases on here seem to show you all are using Javascript classic cases now, have you thought about updating the npm package? I'd be happy to help if I can...

**Comment by Asalem1** [comment]
Hey @cooganb, I'm looking to have an updated version up and running this week. Thanks for the heads up

**Comment by Asalem1** [comment]
@cooganb v0.2.5 should resolve the issues. LMK if you encounter any problems
