### ISSUE TITLE
Impossible to create covers dynamically...

### ISSUE THREAD

**Issue by manodupont** [andyyou/react-coverflow#34]
Anyone ever created dynamically their covers ?

let's say something like this 

```
let pages = [{
        downloadUrl: require('../../public/apple-touch-icon.png')
      },
        {
          downloadUrl: require('../../public/images/avid-wallpapers.jpg')
        }];
      if (pages && pages.length !== 0) {
        return (
          <Coverflow width="960" height="500"
                     displayQuantityOfSide={2}
                     navigation={false}
                     enableScroll={true}
                     clickable={true}
                     active={0}
          >
            {pages.map((page, index) => {
              console.log("Page", index);
              <img key={"image-cover-" + index} src={page.downloadUrl}/>
            })}
          </Coverflow>
        )
      }
```

I always end up with some errors in console.
<img width="1273" alt="screen shot 2017-07-03 at 09 43 59" src="https://user-images.githubusercontent.com/7568033/27795542-8df69c26-5fd4-11e7-8e5e-8a1e2d8bf952.png">

SO you see my two images are created as Page 0 and Page 1 seems to go through, but always end with a props error.

Any idea ?

**Comment by themillhousegroup** [comment]
I found that I while I didn't get errors like yours, the component wouldn't redraw itself properly if the number of covers (aka children) changed.

I've ended up forking this project to fix that: [](https://github.com/themillhousegroup/react-coverflow) - I will create PRs here but I'm not sure this project is really active any more. You can install my fork with npm - check the README in my fork.

**Comment by Asalem1** [comment]
@manodupont I'll take a look at this issue sometime this week - my apologies - I've only recently taken over this repo but it is once again being supported

**Comment by Asalem1** [comment]
@manodupont seems to be related to [#16](https://github.com/andyyou/react-coverflow/issues/16)
