### ISSUE TITLE
TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by alialsaeedi19** [andyyou/react-coverflow#36]
I always get this error : TypeError: Cannot read property 'object' of undefined
even if you try it here https://npm.runkit.com/react-coverflow   and press Run  you will get the same error 

any help please

**Comment by Asalem1** [comment]
@alialsaeedi19 can you pull the most recent branch and let me know if you're still receiving this error?

**Comment by Asalem1** [comment]
resolved with v 0.2.7
