### ISSUE TITLE
Issue with Server Side Rendering - react-coverflow

### ISSUE THREAD

**Issue by fenos** [andyyou/react-coverflow#39]
Hi, thanks for the library!

I'm having an issue loading the `react-coverflow` package into my server side bundle.

When importing `react-coverflow`, webpack compile the server bundle fine.

However, my node server throws the following exception, prior starting:

```
ReferenceError: window is not defined

src/dist/server/server.js:157240
!function(e,n){ true?module.exports=n(__webpack_require__(2),__webpack_require__(276)):"function"==typeof define&&define.amd?define(["react","react-dom"],n):"object"==typeof exports?exports["react-converflow"]=n(require("react"),require("react-dom")):e["react-converflow"]=n(e.React,e.ReactDOM)}("undefined"!=typeof self?self:this,function(__WEBPACK_EXTERNAL_MODULE_13__,__WEBPACK_EXTERNAL_MODULE_39__){return function(e){function n(e){delete installedChunks[e]}function t(e){var n=document.getElementsByTagName("head")[0],t=document.createElement("script");t.type="text/javascript",t.charset="utf-8",t.src=d.p+""+e+"."+G+".hot-update.js",n.appendChild(t)}function c(e){return e=e||1e4,new Promise(function(n,t){if("undefined"==typeof XMLHttpRequest)return t(new Error("No browser support"));try{var c=new XMLHttpRequest,l=d.p+""+G+".hot-update.json";c.open("GET",l,!0),c.timeout=e,c.send(null)}catch(e){return t(e)}c.onreadystatechange=f
```

Which points me to this line of the `dist/react-coverflow.js` file.

```js
var o=window.webpackHotUpdatereact_converflow;window.webpackHotUpdatereact_converflow
```

Example Usage In my code base:
```js
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import CoverFlow from 'react-coverflow';

import style from './SerieCarousel.scss';
import Serie from './Serie';

class SerieCarousel extends PureComponent {
  render() {
    const { series } = this.props;

    const settings = {
      width: 960,
      height: 480,
      displayQuantityOfSide: 2,
      navigation: false,
      enableHeading: false,
      clickable: true,
      active: 0,
      enableScroll: false,
    };

    return (
      <CoverFlow {...settings}>
        {series.map((serie, key) => (
          <div className={style.frame}>
            <Serie serie={serie} key={key} />
          </div>
        ))}
      </CoverFlow>
    );
  }
}

export default SerieCarousel;
```

Is there something that I'm missing to be able to server-side my component with this library?

**Comment by Asalem1** [comment]
Hey @fenos, thanks for the super detailed issue! I'll take a look at the possibility of converting React-Coverflow to make sure it is compatible with server-side rendering. I'll let you know when I've made a PR and it's ready to go.

**Comment by Asalem1** [comment]
@fenos I see. I'll work on it today and get back to you. Thanks for being so patient

**Comment by Asalem1** [comment]
@fenos I'd recommend pulling the most recent version (https://github.com/andyyou/react-coverflow/commit/e2c17f1659d82dbfc677301dc39a39ead0017fd4). I added a conditional statement for rendering the window commands so let me know if it works or not.

**Comment by Asalem1** [comment]
Removed references to document & window in most recent commit, should fix SSR issues (https://github.com/andyyou/react-coverflow/commit/62085c9e6b7dcc00594ce99b34be5e45465cc9c6)

**Comment by oyeanuj** [comment]
@Asalem1 I'm still seeing the same issue as well.. 

@fenos what was your solution?

**Comment by shayanpaul91** [comment]
i am facing the same issue... can you please help me on that
