### ISSUE TITLE
Switching out photos doesn't reset scroll position

### ISSUE THREAD

**Issue by devinholloway** [andyyou/react-coverflow#4]
I use a button bar to swap out and load a different set of images into the cover flow. For example, if the coverflow is currently scrolled to the 20th image, and then I load in a different set of images, it remains on the 20th image.  The new set of images may have less than 20, which puts the component in a weird state.

Essentially, if a new set of images is swapped in, it should reset the scroll position to the center (or optionally) the beginning.

**Comment by Asalem1** [comment]
Hey @devinholloway, could you give me an example of how you're swapping out the sets of images? One solution to this may be setting the state back to 0 when you swap out the image sets, not sure if this functionality needs to be built in

**Comment by Asalem1** [comment]
This functionality shouldn't exist within the plugin. A feasible solution for your implementation would be to simply set the active prop to 0 upon loading a different set of images.
