### ISSUE TITLE
Unable to click on figures

### ISSUE THREAD

**Issue by jculloty** [andyyou/react-coverflow#44]
The NPM version is out of sync with the github version. NPM is 4 months old and missing f386a14fa521c2a741c491dc which fixed the issue.

Note: cloning the project from github and rebuilding "prepublishOnly" fixes the issue.

**Comment by Asalem1** [comment]
Hey @jculloty , thanks for the heads up. I'll take a look at this

**Comment by Asalem1** [comment]
@jculloty, thanks for your patience. I’ve managed to update the dependencies which should resolve the issue. Let me know if it persists
