### ISSUE TITLE
Works only when in focus

### ISSUE THREAD

**Issue by SuhasPai3799** [andyyou/react-coverflow#46]
Is there anyway to have the carousel work even when not in focus?

**Comment by Asalem1** [comment]
@SuhasPai3799, what do you mean by that? Could you please provide me with an example?

**Comment by Asalem1** [comment]
@SuhasPai3799 , did you mean to ask if it's possible to use a setTimeout in order to move the carousel without any user interaction?

**Comment by mattes3** [comment]
Get a ref to the container div and call container.focus() on that ref so that the keyboard events really come through:

componentDidMount() {
        this.updateDimensions();
...
        // set the focus on the container so that keyboard events will come through
        setTimeout(
            () => {
                if (this.myRefs.container) {
                    this.myRefs.container.focus();
                }
            },
            500
        );
    }

and in the render function:

<div  ref={r => this.myRefs.container = r} ... >

**Comment by Asalem1** [comment]
Thanks @mattes3 !
