### ISSUE TITLE
Error after npm install: react-coverflow doesn't work

### ISSUE THREAD

**Issue by eled30** [andyyou/react-coverflow#47]
Hello, 
I have installed your plugin in my react application with npm install, but it gives this error: 
![image](https://user-images.githubusercontent.com/33835622/45751905-16a3c700-bc14-11e8-9644-f529b1cfcecc.png)

I have copied the first example code exactly . What can be the problem?
Thank you very much

**Comment by Asalem1** [comment]
Hi @eled30 , I'm working on getting the repo updated. I'll let you know when it's up and running and get back to you.

**Comment by Asalem1** [comment]
Hey @eled30, thanks for bringing this to my attention. It appears as though react-tap-event-plugin will not work with React versions after 16.4.0

https://github.com/zilverline/react-tap-event-plugin/issues/121.

I'm currently working on updating the package so I'll make sure to remove the package from the upcoming version.
