### ISSUE TITLE
multiple copies of react

### ISSUE THREAD

**Issue by AbhilashDawar** [andyyou/react-coverflow#50]
React is listed as dependency and is creating an issue when it i being used.
Error Details:
![image](https://user-images.githubusercontent.com/25852222/46665458-85f05380-cbe1-11e8-8908-a5be97a99b11.png)

When searched, I found out that there are multiple versions of react in the the project folder.
![image](https://user-images.githubusercontent.com/25852222/46665590-f0a18f00-cbe1-11e8-9be2-842ba529757c.png)

One of the solution provided for the similar issue is to remove "React" from dependency, instead it should be listed as peer-dependency.

**Comment by Asalem1** [comment]
Thanks for sending this through @AbhilashDawar, feel free to submit a PR and I'll take a look at it if you'd like

**Comment by Asalem1** [comment]
Fixed with latest PR:

https://github.com/andyyou/react-coverflow/commit/becd13c02025ac7ecbebc3562211d114cbcbc6e0
