### ISSUE TITLE
While resizing the window screen react-coverflow throws an Uncaught Error

### ISSUE THREAD

**Issue by adityatandon007** [andyyou/react-coverflow#55]
Uncaught Error: findDOMNode was called on an unmounted component.
    at invariant (invariant.js:42)
    at Object.findDOMNode (findDOMNode.js:51)
    at ProxyComponent.updateDimensions (Coverflow.js?2a0d:121)

**Comment by Asalem1** [comment]
thanks, I'll take a look at this

**Comment by Asalem1** [comment]
Fixed with https://github.com/andyyou/react-coverflow/commit/cfd5311b00ceb61dcafd1e843ae56f1bb0d5458a
