### ISSUE TITLE
set background with centered image

### ISSUE THREAD

**Issue by Eesssn** [andyyou/react-coverflow#56]
i want to set main container background with image that shown in center of slider, not using background color. every time user change image (scrolled), background change and show that image behind the image as background and blur it, how could i do that?

**Comment by Asalem1** [comment]
Hey @Eesssn , I'm not quite sure what you're looking to do. Would you mind clarifying your issue?

**Comment by Eesssn** [comment]
<img width="684" alt="capture" src="https://user-images.githubusercontent.com/32749582/52791176-9a57c780-307d-11e9-935a-a1749a4c3159.PNG">
i want to change that grey background behind images, with active image that is in front of images.
i don't want to show grey background instead of that show active image and change background with changing active image.

**Comment by Eesssn** [comment]
> Hey @Eesssn , I'm not quite sure what you're looking to do. Would you mind clarifying your issue?

                               /\
can u help for that  ||

**Comment by Asalem1** [comment]
Aw, I think I understand what you're saying. I can see about integrating that as a future feature

**Comment by meirbr** [comment]
Hey, first of all - thank you.
Is it now possible to change the background color?
