### ISSUE TITLE
react version 0.15.1 tips Only a ReactOwner can have refs.'

### ISSUE THREAD

**Issue by nd888915** [andyyou/react-coverflow#6]
when I delete node_modules/react-coverflow/react and react-dom files ,it works

**Comment by Yyunfan** [comment]
yeah, the same as you

**Comment by xinghul** [comment]
This is caused by multiple copies of React

**Comment by ankitduseja** [comment]
+1

**Comment by Yyunfan** [comment]
well done，we solve it，thx @xinghul
