### ISSUE TITLE
enableHeading depending on media

### ISSUE THREAD

**Issue by bassman2112** [andyyou/react-coverflow#65]
Hi there,

I was curious if there is currently a way to have `enableHeading={true}` with `max-width:900px`, but false < 900px.

Thank you so much for the awesome tool!!!

**Comment by Asalem1** [comment]
Unfortunately the current repo does not support that functionality, but I imagine that it would be possible to integrate a listener onto your project that listens to the window size and conditionally renders the `enableHeading` based on whether the width is > 900px.
