### ISSUE TITLE
I am trying to use active props but is not working 

### ISSUE THREAD

**Issue by BrandonEscamilla** [andyyou/react-coverflow#69]
When I try to use active props it doesn't works. 

<img width="584" alt="Captura de Pantalla 2019-08-15 a la(s) 12 49 32" src="https://user-images.githubusercontent.com/21966716/63114776-4316af00-bf5b-11e9-85b6-6d7386fef9b3.png">
I've changed the number in active but it always focus the same one

**Comment by ladislavjacho** [comment]
+1

**Comment by BrandonEscamilla** [comment]
I already discover how to use it, you just need to use a function to change the active number.

**Comment by ladislavjacho** [comment]
@BrandonEscamilla can you share ur code pls

**Comment by BrandonEscamilla** [comment]
Yeah for sure @ladislavjacho, in my case - after I select one component I wanted to save the state in order to show the same one once you come back. First of all, when the user clicks the image I save the selection in redux, once the user come back I get the data from the store and save it in the state. It wont work if you just use the data from the store or from the state, it appears that Coverflow needs a trigger in order to work so what I did is just set the state in a function that is called by useEffect() and that's how it works. 

PD. I will delete the data-action 

<img width="671" alt="Captura de Pantalla 2019-08-17 a la(s) 9 46 35" src="https://user-images.githubusercontent.com/21966716/63213619-0e7a3300-c0d4-11e9-817f-3de209d7e7cf.png">

**Comment by ladislavjacho** [comment]
IMHO it is not a good approach because if you don’t pass an array into the useEffect Hook, your component will continuously reload repeatedly. Try to fix that in another way - if you pass an empty array it will only update state on the first render, exactly like componentDidMount.

`useEffect( () => { _handleState() }, [] );`

It should work as well. 
Btw I wanted to achieve the same thing.

**Comment by BrandonEscamilla** [comment]
Yeah, I forgot to pass an array, thank you for the recommendation :)

**Comment by ladislavjacho** [comment]
You are welcome. Planets with animated carousel and reflection below gonna look great, gl!

**Comment by BrandonEscamilla** [comment]
I agree! they look really great  🚀

<img width="1421" alt="Captura de Pantalla 2019-08-17 a la(s) 11 29 50" src="https://user-images.githubusercontent.com/21966716/63214798-7b94c500-c0e2-11e9-94c4-0807235a9410.png">

**Comment by Asalem1** [comment]
Hey, sorry for the delay you two. Is this still active? Would anyone like to send up a PR with a fix if one was needed? I've been really swamped with work and would be happy to review a PR

**Comment by davitmargaryan** [comment]
Hi @Asalem1 , the issue is still present, please have a look at [fix](https://github.com/andyyou/react-coverflow/pull/71).

**Comment by adrihle** [comment]
> 
> 
> I agree! they look really great 🚀
> 
> <img alt="Captura de Pantalla 2019-08-17 a la(s) 11 29 50" width="1421" src="https://user-images.githubusercontent.com/21966716/63214798-7b94c500-c0e2-11e9-94c4-0807235a9410.png">

Look super bro, how did u for remove the items background, im trying to do something similar of u, but when i assing a png image wihout background, just appear a shadow box making a background, and someone know how to get the position on scroll up the carousel?
