### ISSUE TITLE
Get/Set Centered/Active Child 

### ISSUE THREAD

**Issue by ankitduseja** [andyyou/react-coverflow#8]
Is there any way to get/set the active/center child number or key?

Setting could be done using a prop which take number/key of the child to be activated/centered. Whereas for getting the active child, a function like onActiveChildChange could be made and param passes the details of the active child.

**Comment by andyyou** [comment]
v0.2.0 I add `active` attribute but seems I leave React a while so I forgot a lot of things I need time to figure out how is the better way to get child for your suggestion

**Comment by Asalem1** [comment]
@ankitduseja the `active` property should be able to handle this.
