### ISSUE TITLE
react-coverflow dont work with SSR Next.JS

### ISSUE THREAD

**Issue by Morozzko** [andyyou/react-coverflow#96]
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
file:///C:/Users/2/WebstormProjects/node_modules/react-coverflow/dist/react-coverflow.js (1:266)

**Comment by fybchristasker** [comment]
it works with next/dynamic

**Comment by luisrabock** [comment]
import dynamic from 'next/dynamic'
const DynamicCoverflow = dynamic(
  () => import('react-coverflow'),
  { ssr: false }
)
